Repository kubernetes-sigs/hydrophone, pull requests merged in 2024-02, with the labels that each got.

#140 test: add tests for args.go
  cmd/root.go
  go.mod
  pkg/common/args.go
  pkg/common/args_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#121 Added development.md
  DEVELOPMENT.md
  README.md
Labels: ok-to-test, approved, cncf-cla: yes, lgtm, size/L

#145 Update go to 1.22
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#124 Updated the readme file
  README.md
Labels: ok-to-test, approved, size/XS, cncf-cla: yes, lgtm

#150 Fixed the default namespace issue
  cmd/root.go
  pkg/common/args.go
  pkg/service/init.go
Labels: ok-to-test, approved, size/XS, cncf-cla: yes, lgtm

#148 Created a spinner for let users wait that the test is running
  pkg/common/args.go
  pkg/common/spinner.go
  pkg/log/logs.go
Labels: ok-to-test, approved, cncf-cla: yes, lgtm, size/L

#153 Set an empty key tolerations to match all tains on node
  pkg/service/init.go
Labels: approved, size/XS, cncf-cla: yes, lgtm

#154 Update README.md
  README.md
Labels: ok-to-test, approved, size/XS, cncf-cla: yes, lgtm

#157 typo and correction in air-gapped.md
  docs/air-gapped.md
Labels: approved, size/XS, cncf-cla: yes, lgtm, kind/documentation

#158 fix: server version parsing
  go.mod
  go.sum
  pkg/common/args.go
  pkg/common/args_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#160 Prepend v to trimmedVersion
  hack/run-e2e.sh
  pkg/common/args.go
  pkg/common/args_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#159 refactor: have a common method for setting defaults and move spinner call to root.go
  cmd/root.go
  pkg/common/args.go
  pkg/common/args_test.go
  pkg/log/logs.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#162 Improved logging for clusterrole and clusterbinding
  pkg/service/init.go
Labels: ok-to-test, approved, cncf-cla: yes, lgtm, size/S
