Repository kubernetes-sigs/hydrophone, pull requests merged in 2024-11, with the labels that each got.

#222 Update to latest k8s version `v1.31.2`
  README.md
  go.mod
  go.sum
  hack/bump-k8s.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#218 feat: SecurityContexts to fullfill PodSecurity policy baseline
  go.mod
  go.sum
  pkg/conformance/deploy.go
Labels: ok-to-test, approved, cncf-cla: yes, lgtm, size/M

#219 feat: created container image
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S
