Repository kubernetes-sigs/hydrophone, pull requests merged in 2024-04, with the labels that each got.

#163 add context handling
  cmd/root.go
  pkg/client/check.go
  pkg/client/client.go
  pkg/client/download.go
  pkg/client/pod_log.go
  pkg/service/init.go
  pkg/service/list_images.go
Labels: ok-to-test, approved, cncf-cla: yes, lgtm, size/M

#164 fix help text for --config flag
  cmd/root.go
  pkg/client/client.go
Labels: ok-to-test, approved, size/XS, cncf-cla: yes, lgtm

#166 remove 2s delay on startup
  pkg/common/args.go
Labels: ok-to-test, approved, size/XS, cncf-cla: yes, lgtm, kind/cleanup

#165 cleanup logging, return errors from pkg/ code
  .github/workflows/update-deps.yml
  cmd/root.go
  pkg/client/check.go
  pkg/client/client.go
  pkg/client/download.go
  pkg/common/args.go
  pkg/service/init.go
  pkg/service/list_images.go
Labels: ok-to-test, approved, cncf-cla: yes, lgtm, size/L

#173 fail boilerplate check if non-compliant files are detected
  hack/boilerplate/boilerplate.py
  pkg/common/spinner.go
Labels: ok-to-test, approved, cncf-cla: yes, lgtm, size/S

#174 prevent broken junit report files
  pkg/client/client.go
Labels: ok-to-test, approved, size/XS, cncf-cla: yes, lgtm

#170 use golangci-lint as linter
  .golangci.yml
  cmd/root.go
  hack/verify-golint.sh
  pkg/client/client.go
  pkg/common/args.go
  pkg/service/init.go
  pkg/service/init_test.go
  pkg/service/list_images.go
Labels: ok-to-test, approved, cncf-cla: yes, lgtm, size/L

#171 append namespace to resources to allow parallel conformance tests
  hack/run-e2e.sh
  pkg/client/download.go
  pkg/service/init.go
Labels: ok-to-test, approved, cncf-cla: yes, lgtm, size/M

#177 mention --cleanup in the developer documentation
  DEVELOPMENT.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#176 hide spinner on -v <= 2, show test logs in realtime with -v >= 6
  cmd/root.go
  docs/air-gapped.md
  hack/run-e2e.sh
  hack/verify-all.sh
  pkg/service/init.go
Labels: ok-to-test, approved, cncf-cla: yes, lgtm, size/M

#180 Exit process if conformance pod ImagePullBackOff.
  pkg/client/check.go
  pkg/common/pod.go
  pkg/service/list_images.go
Labels: ok-to-test, approved, cncf-cla: yes, lgtm, size/M

#179 Handle errors coming from `viper.BindPFlag`
  cmd/root.go
Labels: ok-to-test, approved, cncf-cla: yes, lgtm, size/M

#182 update kind in e2e tests to 0.22
  hack/run-e2e.sh
Labels: approved, size/XS, cncf-cla: yes, lgtm, kind/cleanup

#184 remove redundant gofmt check
  hack/verify-gofmt.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#183 Update update-deps workflow to Go 1.22
  .github/workflows/update-deps.yml
Labels: ok-to-test, approved, size/XS, cncf-cla: yes, lgtm

#186 download a precompiled golangci-lint to save CI time
  hack/verify-golint.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#188 add --continue flag to resume/reconnect to a running conformance test
  DEVELOPMENT.md
  cmd/root.go
Labels: approved, cncf-cla: yes, lgtm, size/S
