Repository kubernetes-sigs/hydrophone, pull requests merged in 2024-01, with the labels that each got.

#79 Add aniruddha2000 as an approver and security contact
  OWNERS
  SECURITY_CONTACTS
Labels: approved, size/XS, cncf-cla: yes, lgtm

#80 Update hydrophone package import paths
  README.md
  go.mod
  main.go
  pkg/client/check.go
  pkg/client/client.go
  pkg/client/download.go
  pkg/client/pod_log.go
  pkg/common/args.go
  pkg/service/init.go
  pkg/service/list_images.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#82 Ensure GH tests are run when PRs are filed
  .github/workflows/test.yml
Labels: approved, size/XS, cncf-cla: yes, lgtm

#83 whoops! we can use sigs.k8s.io
  README.md
  go.mod
  main.go
  pkg/client/check.go
  pkg/client/client.go
  pkg/client/download.go
  pkg/client/pod_log.go
  pkg/common/args.go
  pkg/service/init.go
  pkg/service/list_images.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#84 Add .goreleaser.yaml
  .gitignore
  .goreleaser.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#88 Added dry-run test
  hack/dryrun-e2e.sh
Labels: approved, cncf-cla: yes, size/M

#87 Added go verify suite with go fmt go vet and golint
  Makefile
  hack/verify.sh
  pkg/client/check.go
  pkg/client/client.go
  pkg/common/args.go
  pkg/common/const.go
  pkg/log/logs.go
  pkg/service/init.go
  pkg/service/list_images.go
Labels: approved, cncf-cla: yes, size/L

#90 Fixed CI scripts
  hack/dryrun-e2e.sh
  hack/verify.sh
Labels: approved, size/XS, cncf-cla: yes

#91 added single focus test
  hack/dryrun-e2e.sh
Labels: ok-to-test, approved, cncf-cla: yes, lgtm, size/S

#92 Minor fixes to dryrun-e2e.sh
  hack/dryrun-e2e.sh
Labels: approved, size/XS, cncf-cla: yes, lgtm

#93 fix/readme: minor typo
  README.md
Labels: approved, size/XS, cncf-cla: yes, lgtm

#100 Removing presubmit github actions workflow
  .github/workflows/test.yml
Labels: approved, cncf-cla: yes, lgtm, size/L

#101 Updated the e2e script to be more flexible
  hack/dryrun-e2e.sh
  hack/run-e2e.sh
Labels: approved, cncf-cla: yes, size/L

#102 Very small typo in e2e script
  hack/run-e2e.sh
Labels: approved, size/XS, cncf-cla: yes, lgtm

#103 Changed run-e2e to manage --conformance
  hack/run-e2e.sh
Labels: approved, size/XS, cncf-cla: yes

#99 feat: image version matching
  pkg/common/args.go
  pkg/common/const.go
  pkg/service/init.go
  pkg/service/list_images.go
Labels: ok-to-test, approved, cncf-cla: yes, lgtm, size/S

#105 Initialize CHECK_DURATION in hack/run-e2e script
  hack/run-e2e.sh
Labels: ok-to-test, approved, size/XS, cncf-cla: yes, lgtm

#108 Updated e2e script to better handle focus and skip
  hack/run-e2e.sh
Labels: approved, size/XS, cncf-cla: yes

#114 Removed unwanted arguments and parametres
  main.go
  pkg/service/list_images.go
Labels: ok-to-test, approved, size/XS, cncf-cla: yes, lgtm

#115 Removed github workflow periodics in favor of prow
  .github/workflows/periodic_conformance.yml
  .github/workflows/periodic_e2e.yml
Labels: approved, cncf-cla: yes, lgtm, size/L

#116 Adding evaluation for number of tests
  hack/run-e2e.sh
Labels: approved, cncf-cla: yes, size/S

#122 Makefile update
  Makefile
Labels: ok-to-test, approved, size/XS, cncf-cla: yes, lgtm

#125 Remove redundant error check in client.PrintE2ELogs()
  pkg/client/check.go
Labels: ok-to-test, approved, size/XS, cncf-cla: yes, lgtm

#129 fix: typo and copyright
  cmd/root.go
Labels: ok-to-test, approved, cncf-cla: yes, lgtm, size/S

#132 Add rakshitgondwal as reviewer
  OWNERS
Labels: approved, size/XS, cncf-cla: yes, lgtm

#126 Add reetasingh as reviewer
  OWNERS
Labels: ok-to-test, approved, size/XS, cncf-cla: yes, lgtm

#133 Add rakshitgondwal as reviewer
  OWNERS
Labels: approved, size/XS, cncf-cla: yes

#137 Minor changes to clarify CI failures
  Makefile
  hack/verify-boilerplate.sh
  hack/verify-golint.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#135 Throw fatal error and ask user to run cleanup when a k8s resource already exists in the cluster
  pkg/service/init.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#136 Add support for Additional Conformance Test Flags
  cmd/root.go
  pkg/common/args.go
  pkg/common/args_test.go
  pkg/service/init.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#138 chore: Remove unneeded params passed to common.ValidateArgs function
  cmd/root.go
  pkg/common/args.go
  pkg/common/args_test.go
Labels: approved, size/XS, cncf-cla: yes, lgtm

#139 feat: allow to customize the namespace
  README.md
  cmd/root.go
  pkg/client/check.go
  pkg/client/client.go
  pkg/client/download.go
  pkg/client/pod_log.go
  pkg/common/args.go
  pkg/common/const.go
  pkg/service/init.go
Labels: ok-to-test, approved, cncf-cla: yes, lgtm, size/L
