Repository kubernetes-sigs/hydrophone, pull requests merged in 2025-05, with the labels that each got.

#239 Bump Kubernetes on (05/05/2025)
  go.mod
  go.sum
Labels: approved, size/XS, cncf-cla: yes, lgtm

#232 add unit test for namespacedName function
  pkg/conformance/runner_test.go
Labels: ok-to-test, approved, cncf-cla: yes, lgtm, size/M

#243 Bump Kubernetes on (05/19/2025)
  README.md
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S

#247 bumps update-deps go to match go.mod
  .github/workflows/update-deps.yml
Labels: ok-to-test, approved, size/XS, cncf-cla: yes, lgtm

#242 set time to UTC
  pkg/log/logs.go
Labels: ok-to-test, approved, size/XS, cncf-cla: yes, lgtm
